name: Build Cross-Platform (Linux, Windows, macOS)

on:
  push:
    tags:
      - "*.*.*.*"
      - "*.*.*.*-nightly"

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      ghc: "9.12.2"
      cabal: "3.14.2.0"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            name: zwirnmill-${{ github.ref_name }}-x86_64-linux
            is_linux: true
            cabal_flags: "--enable-executable-stripping --disable-shared --enable-executable-static --ghc-options='-split-sections -optl-static'"

          - os: windows-latest
            arch: x86_64
            name: zwirnmill-${{ github.ref_name }}-x86_64-windows.exe
            is_windows: true
            cabal_flags: "--enable-executable-stripping"

          - os: macOS-15-intel
            arch: x86_64
            name: zwirnmill-${{ github.ref_name }}-x86_64-macos
            is_mac: true
            cabal_flags: "--enable-executable-stripping"

          - os: macOS-latest
            arch: arm64
            name: zwirnmill-${{ github.ref_name }}-arm64-macos
            is_mac: true
            cabal_flags: "--enable-executable-stripping"

    steps:
    - name: (Linux) Install Native Deps
      if: matrix.is_linux
      run: |
        sudo add-apt-repository -y ppa:pipewire-debian/pipewire-upstream
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          bash curl git make gcc g++ g++-multilib sudo tar xz-utils libgmp-dev libffi-dev libncurses-dev \
          pkg-config libasound2-dev libjack-jackd2-dev libpipewire-0.3-dev libspa-0.2-dev \
 
    - name: Checkout code  
      run: | 
           git clone https://codeberg.org/polymorphicengine/haskell-doux
           git clone https://codeberg.org/uzu/zwirn

    - name: If nightly release, checkout dev branch
      if: contains(github.ref_name, 'nightly')
      run: cd zwirn && git checkout dev

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Set up Haskell (GHC 9.12.2)
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ env.ghc }}
        cabal-version: ${{ env.cabal }}

    - name: (Linux) install dependencies
      if: matrix.is_linux
      run: |
        sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream -y
        sudo apt-get update
        sudo apt-get install -y libpipewire-0.3-dev libasound2-dev

    - name: (Windows) Install Rust GNU Target
      if: ${{ matrix.is_windows }}
      run: rustup target add x86_64-pc-windows-gnu
        
    - name: (Linux/macOS) Build Rust Static Library
      if: matrix.is_linux || matrix.is_mac
      shell: bash
      run: |
        cd haskell-doux/doux-ffi
        cargo build --release

    - name: (Windows) Build Rust Static Library
      if: matrix.is_windows
      shell: bash
      run: |
        cd haskell-doux/doux-ffi
        cargo build --release --target x86_64-pc-windows-gnu

    - name: (Linux/macOS) Generate cabal.project.local
      if: matrix.is_linux || matrix.is_mac
      shell: bash
      run: |
        cd zwirn
        rm cabal.project.local
        TARGET_PATH="${{ github.workspace }}/haskell-doux"
    
        echo "ignore-project: False" > cabal.project.local
        echo "package *" >> cabal.project.local
        echo "  ghc-options: -split-sections" >> cabal.project.local
        echo "  gcc-options: -fdata-sections -ffunction-sections" >> cabal.project.local
        echo "" >> cabal.project.local
    
        echo "packages:" >> cabal.project.local
        echo "   ." >> cabal.project.local
        echo "   $TARGET_PATH" >> cabal.project.local
        echo "" >> cabal.project.local
    
        echo "package haskell-doux" >> cabal.project.local
        echo "  extra-lib-dirs: $TARGET_PATH/doux-ffi/target/release" >> cabal.project.local
    
        cat cabal.project.local

    - name: (Windows) Generate cabal.project.local
      if: matrix.is_windows
      shell: bash
      run: |
        cd zwirn
        rm cabal.project.local
        RAW_PATH="${{ github.workspace }}/haskell-doux"
        WIN_PATH=$(echo "$RAW_PATH" | sed 's/\//\\/g')
      
        echo "ignore-project: False" > cabal.project.local
        echo "package *" >> cabal.project.local
        echo "  ghc-options: -split-sections" >> cabal.project.local
        echo "  gcc-options: -fdata-sections -ffunction-sections" >> cabal.project.local
        echo "" >> cabal.project.local
    
        echo "packages:" >> cabal.project.local
        echo "   ." >> cabal.project.local
        echo "   $WIN_PATH" >> cabal.project.local
        echo "" >> cabal.project.local
    
        echo "package haskell-doux" >> cabal.project.local
        echo "  extra-lib-dirs: $WIN_PATH\\doux-ffi\\target\\x86_64-pc-windows-gnu\\release" >> cabal.project.local
    
        cat cabal.project.local
          

    - name: Update cabal cache
      run: cabal update  
      shell: bash
      
    - name: Dry run of build
      run: cd zwirn && cabal build zwirnmill ${{ matrix.cabal_flags }}

    - name: Restore cached dependencies
      uses: actions/cache/restore@v4
      id: cache
      env:
        key: ${{ contains(github.ref_name, 'nightly') }}-${{ runner.os }}-ghc-${{ env.ghc }}-cabal-${{ env.cabal }}
      with:
        path: /github/home/.local/state/cabal/store
        key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
        restore-keys: ${{ env.key }}-

    - name: Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
      if: steps.cache.outputs.cache-hit != 'true'
      run: cd zwirn && cabal build zwirnmill ${{ matrix.cabal_flags }}
      # Cache dependencies already here, so that we do not have to rebuild them should the subsequent steps fail.
    - name: Save cached dependencies
      uses: actions/cache/save@v4
       # If we had an exact cache hit, trying to save the cache would error because of key clash.
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: /github/home/.local/state/cabal/store
        key: ${{ steps.cache.outputs.cache-primary-key }}

    - name: cabal build
      run: cd zwirn && cabal build zwirnmill ${{ matrix.cabal_flags }}
      
    - name: set build location to var
      run: cd zwirn && echo "bin_path=$(cabal list-bin zwirnmill)" >> "$GITHUB_ENV"

    - name: make directory
      run: mkdir build

    - name: move executable
      run: mv "$bin_path" build/${{ matrix.name }}
        
    - name: strip executable
      run: cd build && strip ${{ matrix.name }}
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/${{ matrix.name }}
