name: Build Cross-Platform (Linux, Windows, macOS)

on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            is_linux: true

          - os: windows-latest
            arch: x86_64
            is_windows: true

          - os: macOS-15-intel
            arch: x86_64
            is_mac: true

          - os: macOS-latest
            arch: arm64
            is_mac: true

    steps:
    - name: (Linux) Install Native Deps
      if: matrix.is_linux
      run: |
        apt-get update
        sudo apt-get install -y --no-install-recommends \
          bash curl git make gcc g++ g++-multilib sudo tar xz-utils libgmp-dev libffi-dev libncurses-dev \
          pkg-config libasound2-dev libjack-jackd2-dev libpipewire-0.3-dev \
 
    - name: Checkout code  
      run: git clone https://codeberg.org/polymorphicengine/haskell-doux

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Set up Haskell (GHC 9.12.2)
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.12.2'
        cabal-version: '3.14.2.0'


    - name: Build Rust Static Library
      shell: bash
      run: |
        cd haskell-doux/doux-ffi
        cargo build --release

    - name: (Linux/macOS) Generate cabal.project.local
      if: matrix.is_linux || matrix.is_mac
      shell: bash
      run: |
        cd haskell-doux
        rm cabal.project.local
        echo "package haskell-doux" > cabal.project.local
        echo "  extra-lib-dirs: ${{ github.workspace }}/haskell-doux/doux-ffi/target/release" >> cabal.project.local
        cat cabal.project.local

    - name: (Windows) Generate cabal.project.local
      if: matrix.is_windows
      shell: bash
      run: |
        cd haskell-doux
        rm cabal.project.local
        RAW_PATH="${{ github.workspace }}/haskell-doux/doux-ffi/target/release"
        WIN_PATH=$(echo "$RAW_PATH" | sed 's/\//\\/g')
        
        echo "package haskell-doux" > cabal.project.local
        echo "  extra-lib-dirs: $WIN_PATH" >> cabal.project.local
        cat cabal.project.local

    - name: Build Haskell Project
      shell: bash
      run: |
        cd haskell-doux
        cabal update
        cabal build
